### ISSUE TITLE
[Task1] Parallelization of Actions

### ISSUE THREAD

**Issue by elb-dev** [North-Seattle-College/ad440-winter2021-tuesday-repo#286]

**Comment by elb-dev** [comment]
# What:
Parallelization of Github Actions
# How to use:
In .github/workflows, a test file can be set up to run multiple times using the same basic format.
For any particular job, the strategy can be set, with a number of parallel jobs, as well as a matrix of defined variables that are changed with each re-run of the job, in this case being the test files under testing.
Example:
```
jobs:
  artillery_tests:
    name: Artillery Tests
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      max-parallel: 1
      matrix:
        file: 
          - ./testing/artillery/artillery-users.yaml
          - ./testing/artillery/artillery-users-id.yml
          - ./testing/artillery/artillery-users-id-tasks.yml
          - ./testing/artillery/artillery-users-id-tasks-id.yml
```
The line called 'file' can be set by the developer, and called upon later on in the code.

## Why:
This will help designate what files run in what order, will keep jobs from running simultaneously, and will organize code so it does not repeat unecessarily.

# Time:
3 hours researching
8 hours writing and testing
1 hours communicating with team members to try to solve problems
