### ISSUE TITLE
Convert the SQL injection test into GitHub Action

### ISSUE THREAD

**Issue by RayWu222** [North-Seattle-College/ad440-winter2021-tuesday-repo#297]

**Comment by RayWu222** [comment]
Date | Activity | Time Spent
-- | -- | --
3/12/2021 |Researched the basics of SQL injection | 2 hour
3/13/2021 |Researched GitHub Action| 2 hours
3/14/2021 |Team Meeting| 4 hours
3/15/2021 |Work on convert SQL injection test into GitHub Action| 2 hours

**Comment by RayWu222** [comment]
```
name: SQL-Injection-Test-HTTPTriggerUsers-Tasks
on:
  push:

jobs:
  injection-test:
    name: SQL Inject on GET to fetch all user Tasks
    runs-on: ubuntu-latest

    steps:
    - name: GET all users tasks
      uses: distributor/workflow-webhook
      with:
        url: "https://nsc-func-dev-usw2-tuesday.azurewebsites.net/api/users" UNION SELECT taskId, taskUserId, title, taskDescription FROM tasks/tasks
    - name: GET all users email and passwords
      uses: distributor/workflow-webhook
      with:
        url: "https://nsc-func-dev-usw2-tuesday.azurewebsites.net/api/users" UNION SELECT userid, userid, email, userpassword FROM users/tasks"
```

**Comment by RayWu222** [comment]
Unable to test POST because of  Parameterized Queries is preventing SQL injection according to this article. 
HttpTriggerUsers has secured implementation for POST method. 


https://cheatsheetseries.owasp.org/cheatsheets/SQL_Injection_Prevention_Cheat_Sheet.html#defense-option-1-prepared-statements-with-parameterized-queries. 

![SQL1](https://user-images.githubusercontent.com/48284351/111256429-490cc000-85d6-11eb-9837-26f0edfb1dbf.PNG)

**Comment by RayWu222** [comment]
Unable to test my GitHub Action at this moment due to 500 error for HttpTriggerUsers. 

Here the code for GET Method

GitHub Action for SQL Injection for GET
```
name: SQL-Injection-Test-HTTPTriggerUsers
on:
  push:

jobs:
  injection-test:
    name: SQL Inject on GET to fetch all user Tasks
    runs-on: ubuntu-latest

    steps:
    - name: GET all users 
      uses: distributor/workflow-webhook
      with:
        url: "https://nsc-func-dev-usw2-tuesday.azurewebsites.net/api/users" UNION SELECT userId, email, userPassword, firstName,lastName FROM users/tasks
```
