### ISSUE TITLE
Artillery 40 requests without cache for  /users

### ISSUE THREAD

**Issue by sunshinejen** [North-Seattle-College/ad440-winter2021-tuesday-repo#342]
### To run artillery test for 40 requests for 5 min without cache for /users:

1. Navigate to your resource group (nsc-rg-xxxx) 
2. Select Function App (nsc-func-dev-xxxx) 
3. On the left hand side under **Settings** select Configuration 
4. Select CACHE_TOGGLE and change value to **False**,  click OK
5. Then make sure to click on  **SAVE** to update application settings otherwise it will not change to the desired value
<img width="925" alt="sprint6ss" src="https://user-images.githubusercontent.com/35351160/111933721-45b58080-8a7d-11eb-9cd5-1ee034d3e5a0.png">
6. Navigate to the artillery folder then run

`artillery run --output report.json name-of-your-file.yaml`

example yaml test file:
```
config:
  target: "https://nsc-func-dev-usw2-tuesday.azurewebsites.net"
  phases:
    - duration: 300
      arrivalRate: 40
      name: " Sprint 6 Performance Test"
scenarios:
  - flow:
      - post:
          url: "/api/users"
          json:
             name: "name" 

```
_This will create a report.json in the artillery folder. Since we were not creating a PR we opted to easily create a report vs running the GitHub actions to save/upload the report to the Azure container._ 

7. **Remember to revert the CACHE_TOGGLE to True in Azure and save changes.** 

**Snippet of report:**
```
Summary report @ 17:26:35(-0700) 2021-03-23
 Scenarios launched: 12000
 Scenarios completed: 1937
 Requests completed: 1937
 Mean response/sec: 28.54
 Response time (msec):
  min: 143.4
  max: 119881.6
  median: 44739.2
  p95: 113046.8
  p99: 119008.8
 Scenario counts:
  0: 12000 (100%)
 Codes:
  422: 1937
 Errors:
  ESOCKETTIMEDOUT: 10063
```

| Date | Activity| Time |
| :---:        |     :---:      |     :---: |
| 3/19   | Group discussion on time to meet for testing  | 30min    |
| 3/21   | Created task on Github    | 5 min    |
| 3/21    | Running test/team meeting/documentation  | 3 hours   |
